#!/bin/bash

## Description: Backup db
## Usage: db-backup
## Example: "ddev db-backup"

mkdir -p ./.ddev/backup

rm -f ./.ddev/backup/mysql-db.sql.gz

ddev export-db -f ./.ddev/backup/mysql-db.sql.gz
