#!/bin/bash

## Description: Restore fileadmin folder from .ddev/backup/fileadmin.tar.gz
## Usage: fileadmin-restore
## Example: "ddev fileadmin-restore"

set -x

mv ./public/fileadmin ./public/fileadmin-org

tar -xzvf ./.ddev/backup/fileadmin.tar.gz

rm -rf ./public/fileadmin-org
