#!/bin/bash

## Description: Backup fileadmin folder to .ddev/backup/fileadmin.tar.gz
## Usage: fileadmin-backup
## Example: "ddev fileadmin-backup"

set -x

ddev exec mkdir -p ./.ddev/backup

ddev exec rm -f ./.ddev/backup/fileadmin.tar.gz

ddev exec tar -czvf ./.ddev/backup/fileadmin.tar.gz --exclude="_processed_" ./public/fileadmin

