#!/bin/bash

## Description: Restore fileadmin folder
## Usage: fileadmin-restore
## Example: "ddev fileadmin-restore"

mv ./public/fileadmin ./public/fileadmin-org

tar -xzvf ./.ddev/backup/fileadmin.tar.gz

ddev typo3cms cache:flush

ddev typo3cms cleanup:updatereferenceindex

rm -rf ./public/fileadmin-org
