#!/usr/bin/env bash

## Description: Run typo3 scheduler:run on every minute
## Usage: cron
## Example: "ddev cron"

while true
do
  sleep 60
  /var/www/html/public/typo3/sysext/core/bin/typo3 scheduler:run
  echo 'cron done'
done
